---
- name: install sensu apt key
  apt_key: id=7580C77F url=http://repos.sensuapp.org/apt/pubkey.gpg

- name: add the sensu apt repo
  apt_repository: repo='deb http://repos.sensuapp.org/apt sensu main'
                  state=present
                  update_cache=yes

- name: install sensu
  apt: pkg=sensu

- name: install sensu-plugin gem
  gem: name=sensu-plugin user_install=no include_dependencies=yes state=latest

- name: sensu sudoers
  template: src=monitoring/sensu-sudoers dest=/etc/sudoers.d/sensu owner=root
            group=root mode=0440

- name: ensure /etc/sudoers.d/sensu permissions are 0440
  file: path=/etc/sudoers.d/sensu mode=0440

- name: sensu cert directory
  file: dest=/etc/sensu/ssl state=directory owner=sensu mode=0750

- name: install sensu cert
  template: dest=/etc/sensu/ssl/cert.pem src=monitoring/sensu-client-cert.pem
            owner=root group=sensu mode=0640
  notify: restart sensu-client
  when: monitoring.client_cert is defined

- name: install sensu key
  template: dest=/etc/sensu/ssl/key.pem src=monitoring/sensu-client-key.pem
            owner=root group=sensu mode=0640
  notify: restart sensu-client
  when: monitoring.client_key is defined

- name: disable embedded ruby
  lineinfile: dest=/etc/default/sensu regexp=^EMBEDDED_RUBY
              line=EMBEDDED_RUBY=false
  notify: restart sensu-client

- name: sensu client config
  template: src=monitoring/config.json dest=/etc/sensu/config.json owner=root
            group=root
            mode=0444
  notify: restart sensu-client

- name: sensu monitoring credentials
  template: dest=/etc/sensu/stackrc src=etc/sensu/stackrc
            owner=root group=sensu mode=0640
  when: monitoring.openstack.user is defined

- name: load monitoring credentials
  lineinfile: dest=/etc/default/sensu regexp="^\. /etc/sensu/stackrc"
              line=". /etc/sensu/stackrc"
  notify: restart sensu-client
  when: monitoring.openstack.user is defined

- name: enable and start sensu-client
  service: name=sensu-client state=started enabled=yes

- name: install sensu plugin pip modules
  pip: name=sensu_plugin version=0.1.0

- name: sensu conf dir
  file: dest=/etc/sensu/conf.d/checks state=directory owner=root mode=0755

- name: sensu plugins dir
  file: dest=/etc/sensu/plugins state=directory owner=root

- name: copy sensu plugins
  copy: src={{ item }} dest=/etc/sensu/plugins mode=0755
  with_fileglob: sensu_plugins/*

- name: cpu check
  sensu_check: name=cpu plugin=check-cpu.rb args='-w 80 -c 90 -p kvm'
  notify: restart sensu-client

- name: disk check
  sensu_check: name=disk plugin=check-disk.rb
  notify: restart sensu-client

- name: ntpd check
  sensu_process_check: service=ntpd
  notify: restart sensu-client

- name: ntp-offset check
  sensu_check: name=ntp-offset plugin=check-ntp.rb
  notify: restart sensu-client

- name: vmstat metrics check
  sensu_metrics_check: name=vmstat-metrics plugin=vmstat-metrics.rb
                       args='--scheme {{ monitoring.graphite.host_prefix }}'
  notify: restart sensu-client

- name: load metrics check
  sensu_metrics_check: name=load-metrics plugin=load-metrics.rb
                       args='--scheme {{ monitoring.graphite.host_prefix }}'
  notify: restart sensu-client

- name: syslog check
  sensu_check: name=syslog-socket plugin=check-syslog-socket.rb
  notify: restart sensu-client

- name: memory check
  sensu_check: name=memory plugin=check-mem.sh
               args="-w {{ monitoring.checks.memory.warning }} -c {{ monitoring.checks.memory.critical }}"
  notify: restart sensu-client

- name: check nbd devices in use
  sensu_check: name=nbd-in-use plugin=check-nbd-in-use.sh
  notify: restart sensu-client

- name: check for files opened by multiple nbd
  sensu_check: name=nbd-not-unique plugin=check-nbd-nonunique.sh
  notify: restart sensu-client

- name: memory metrics check
  sensu_metrics_check: name=memory-metrics plugin=memory-metrics.rb
                       args='--scheme {{ monitoring.graphite.host_prefix }}'
  notify: restart sensu-client

- name: network metrics check
  sensu_metrics_check: name=network-metrics plugin=metrics-net.rb
                       args='--scheme {{ monitoring.graphite.host_prefix }}'
  notify: restart sensu-client

- name: log files greater than 1gb check
  sensu_check: name=log_file_size plugin=check-for-large-files.sh
               args='-d /var/log -s 1048576'
  notify: restart sensu-client

- name: log scanning caching dir
  file: path=/var/cache/check-log owner=sensu state=directory

- name: enable log scanning
  sensu_check: name=check-log-{{ item }} plugin=check-log.rb use_sudo=true
               auto_resolve=false interval=60
               args="-f /var/log/upstart/{{ item }}.log -q ERROR --silent"
  with_items: logs_to_scan
  when: monitoring.scan_for_log_errors
  notify: restart sensu-client

- name: disable log scanning
  file: path=/etc/sensu/conf.d/checks/check-log-{{ item }}.json state=absent
  with_items: logs_to_scan
  when: monitoring.scan_for_log_errors == false
  notify: restart sensu-client

- name: raid check
  sensu_check: name=check-raid plugin=check-raid.sh interval=300 occurrences=1
  notify: restart sensu-client

- name: kernel-options
  sensu_check: name=kernel-options plugin=check-kernel-options.rb
  notify: restart sensu-client

